// Package materialize renders the knowledge plane into the tool-agnostic
// injectable form: a single materialized.md pulled into agent context via a
// CLAUDE.md/AGENTS.md import line. This is the import half of the adapter
// story — one renderer serves every tool that reads the converging context
// standards (docs/design-v2.md §4.2).
package materialize

import (
	"fmt"
	"os"
	"strings"

	"github.com/A4ever369/Stillroom/internal/ir"
)

// ImportLine is the reference a repo's CLAUDE.md needs so agents load the
// materialized context. AGENTS.md consumers can use a plain relative link.
const ImportLine = "@" + ir.DirName + "/materialized.md"

const header = `<!-- Generated by still materialize — DO NOT EDIT BY HAND.
     Source of truth: ` + ir.DirName + `/facts/ and ` + ir.DirName + `/playbooks/.
     Regenerate with: still materialize -->

# Team Context

Knowledge distilled from this team's AI coding sessions. Each item links back
to its evidence. Treat facts as project ground truth unless contradicted by
the code in front of you.

Anything under "Shared with you" came from someone else's project and is
quoted, not asserted — see the note there.
`

// Run renders materialized.md and writes it, returning a one-line summary.
func Run(s ir.Store) (string, error) {
	content, summary, err := Render(s)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(s.MaterializedPath(), []byte(content), 0o644); err != nil {
		return "", err
	}
	return summary, nil
}

// Render produces materialized.md's exact bytes without writing them, plus a
// one-line summary. Only active facts are injected; superseded and disputed
// stay in files as history (§3.1). Rendering is deterministic so repeated runs
// produce no git noise — which is also what lets `--check` detect drift by
// comparing this output against the committed file.
func Render(s ir.Store) (string, string, error) {
	facts, badFacts, err := s.LoadFacts()
	if err != nil {
		return "", "", err
	}
	playbooks, badPbs, err := s.LoadPlaybooks()
	if err != nil {
		return "", "", err
	}

	var b strings.Builder
	b.WriteString(header)

	active := 0
	for _, f := range facts {
		if f.Status != ir.StatusActive {
			continue
		}
		if active == 0 {
			b.WriteString("\n## Facts\n\n")
		}
		active++
		fmt.Fprintf(&b, "- **%s**", f.ID)
		if f.Scope != "" && f.Scope != "global" {
			fmt.Fprintf(&b, " _(%s)_", f.Scope)
		}
		b.WriteString(": ")
		b.WriteString(strings.ReplaceAll(strings.TrimSpace(f.Body), "\n", " "))
		if f.Confidence != ir.ConfidenceHigh {
			fmt.Fprintf(&b, " _[confidence: %s]_", f.Confidence)
		}
		fmt.Fprintf(&b, " <!-- src: %s @ %s -->\n", f.Source, f.ObservedAt.Format("2006-01-02"))
	}

	if len(playbooks) > 0 {
		b.WriteString("\n## Playbooks\n\n")
		b.WriteString("Full recipes live in `" + ir.DirName + "/playbooks/`. Read the file before executing one.\n\n")
		for _, p := range playbooks {
			fmt.Fprintf(&b, "- **%s** — %s (`%s/playbooks/%s`)\n", p.ID, p.Title, ir.DirName, p.Filename())
		}
	}

	shared := renderReceived(&b, loadReceived(s))

	for name, err := range badFacts {
		fmt.Fprintf(&b, "\n<!-- WARNING: unparseable fact %s: %v -->", name, err)
	}
	for name, err := range badPbs {
		fmt.Fprintf(&b, "\n<!-- WARNING: unparseable playbook %s: %v -->", name, err)
	}

	summary := fmt.Sprintf("%d active facts, %d playbooks", active, len(playbooks))
	if shared > 0 {
		summary += fmt.Sprintf(", %d shared with you", shared)
	}
	return b.String(), summary, nil
}

// EnsureImport idempotently appends the materialized-context import to the
// given context file (CLAUDE.md / AGENTS.md), creating it if absent.
func EnsureImport(contextFile string) (bool, error) {
	data, err := os.ReadFile(contextFile)
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if strings.Contains(string(data), ImportLine) {
		return false, nil
	}
	content := string(data)
	if content != "" && !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	content += "\n## Team Context\n\nSee " + ImportLine + "\n"
	if err := os.WriteFile(contextFile, []byte(content), 0o644); err != nil {
		return false, err
	}
	return true, nil
}
